# Generated by Django 5.0.2 on 2024-03-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_chatmessages_room_message_chatmessages_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomname',
            field=models.SlugField(null=True),
        ),
    ]
