# Generated by Django 5.0.2 on 2024-04-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
